### ISSUE TITLE
Combat crashing

### ISSUE THREAD

**Issue by DaDarkWizard** [DaDarkWizard/TextAdventure#1]
Entering combat alone, no one else was fighting. Had to restart server.

**Comment by AiryTheDragon** [comment]
Example of the Bug:
![BattlePopUp12-15-19](https://user-images.githubusercontent.com/58800410/70889581-f3033400-1fb0-11ea-8fd3-03904910db47.png)

**Comment by AiryTheDragon** [comment]
I've added some console output error checking on this and looked through more of the code.  If I restore a previously made character, it does not freeze up like this, so this bug seems like it has something to do with the new character creation process, maybe some reference not getting changed (or getting changed when it is not expected to)

**Comment by DaDarkWizard** [comment]
Outdated
